name: "Web server"
serverType: "web"
address: "194.163.166.220"
port: 5000
JWTPassword: "secret"
debug: true
certFile: "/etc/letsencrypt/live/sivr.info/cert.pem"
keyFile: "/etc/letsencrypt/live/sivr.info/privkey.pem"