### Ping
POST https://127.0.0.1:8081/restful/info/ping HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNRCI6dHJ1ZSwiYWRtaW4iOnRydWUsImV4cCI6MTYwODkzMjIxOSwiaW5zdGl0dXRpb25faWQiOiI3NTYwM2RkNi1lMGY0LTRlNTMtOTNjZS1hNjRkZTNmZTRhOWUiLCJpbnN0aXR1dGlvbl9pcF9hZGRyZXNzIjoiMTI3LjAuMC4xIiwiaW5zdGl0dXRpb25fcG9ydF9udW1iZXIiOjgwODEsIm9yaWdfaWF0IjoxNjA4OTMxOTE5LCJzdXBlcnVzZXIiOmZhbHNlLCJ1c2VyX2lkIjoiNWU0ZTdhYzUtNTQ3NS00ZDIwLTgzOTItMTc4ZDUwMThkOGZhIn0.Onw1wcSXMGhAymlOKSeQMSYDTnRsxaqpLPE4p3XJRGI