### Ping
POST https://127.0.0.1:8082/restful/info/ping HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNRCI6dHJ1ZSwiYWRtaW4iOnRydWUsImV4cCI6MTU4NTY4MDk5MSwiaW5zdGl0dXRpb24iOiJGRVIiLCJpbnN0aXR1dGlvbl9pcF9hZGRyZXNzIjoiMTI3LjAuMC4xIiwiaW5zdGl0dXRpb25fcG9ydF9udW1iZXIiOjgwODEsIm9yaWdfaWF0IjoxNTg1NjgwNjkxLCJzdXBlcnVzZXIiOmZhbHNlLCJ1c2VyaWQiOiI1ZTRlN2FjNS01NDc1LTRkMjAtODM5Mi0xNzhkNTAxOGQ4ZmEifQ.ONzr53uIHV_Ts7-k4jxY87Sjzv-DbmxBb8O_rpmFQ4g
